image: Visual Studio 2022
version: 1.0.{build}
configuration: Release

init:
- if "%APPVEYOR_REPO_NAME%" == "JeremyAnsel/ZtPatcher" if "%APPVEYOR_REPO_BRANCH%"=="master" if not defined APPVEYOR_PULL_REQUEST_NUMBER set DEPLOY=True

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

before_build:
- nuget restore Zt\Zt.sln

build:
  project: Zt\Zt.sln
  verbosity: minimal

after_build:
- Zt\build-dist.cmd

artifacts:
- path: Zt\dist
  name: ZtCreatorPatcher-$(APPVEYOR_BUILD_VERSION)
  type: zip
